# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2974b9290ad323cbece62d5d3330ba3c12c52e23ff9b197b197dd0748d1ea2dca94c25d364ebe5d3e7c32128fae329a8f5ad94cb9fda53143d450453d8095134

test:
  secret_key_base: 1d7b0b67e3cb333da74f61d67d6bf7771e517f116a3f4a1cc83be5de2217799bb78fa80d08b6bd4e9627296d93e764f2f788bec00593aeddfd8b19dff7f97890

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
